defaults: &defaults
  host: 127.0.0.1
  port: 27017

development:
  <<: *defaults
  database: sentido-development

test:
  <<: *defaults
  host: 192.168.1.101
  database: sentido-development

# set these environment variables on your prod server
production:
  uri: <%= ENV['MONGOHQ_URL'] %>
  database: sentido-production
  #username: <%= ENV['MONGO_USERNAME'] %>
  #password: <%= ENV['MONGO_PASSWORD'] %>
